### ISSUE TITLE
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent at io.github.satoshinm.WebSandboxMC.bukkit.WebSandboxPlugin$1.run(WebSandboxPlugin.java:56)

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/WebSandboxMC#95]
17:18:39 [WARNING] [WebSandboxMC] Task #13 for WebSandboxMC v1.10.3 generated an exception
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at io.github.satoshinm.WebSandboxMC.bukkit.WebSandboxPlugin$1.run(WebSandboxPlugin.java:56)
	at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:777)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:614)

**Comment by satoshinm** [comment]
1.5.2. Works in 1.8.3, broken in 1.9.0. Changes: https://github.com/satoshinm/WebSandboxMC/releases/tag/v1.9.0. Broke with https://github.com/satoshinm/WebSandboxMC/commit/4379f15ea8841b427a2892eed97bc32b9ba3d64c. net/md_5/bungee/api/chat/BaseComponent is not directly referenced but is the superclass of import net.md_5.bungee.api.chat.TextComponent.
